charactercollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('characters/', views.characters_index, name='characters_index'),
    path('characters/<int:character_id>/', views.characters_detail, name='characters_detail'),
    path('characters/create/', views.CharacterCreate.as_view(), name='characters_create'),
    path('characters/<int:pk>/update', views.CharacterUpdate.as_view(), name='characters_update'),
    path('characters/<int:pk>/delete', views.CharacterDelete.as_view(), name='characters_delete'),
    path('characters/<int:character_id>/add_title/', views.add_title, name='add_title'),
    path('medium/create/', views.MediumCreate.as_view(), name='medium_create'),
    path('medium/<int:pk>/', views.MediumDetail.as_view(), name='medium_detail'),
    path('mediums/', views.MediumList.as_view(), name='medium_index'),
    path('mediums/<int:pk>/update/', views.MediumUpdate.as_view(), name='medium_update'),
    path('mediums/<int:pk>/delete/', views.MediumDelete.as_view(), name='medium_delete'),
    path('characters/<int:character_id>/assoc_medium/<int:medium_id>/', views.assoc_medium, name='assoc_medium'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Medium(models.Model):
  medium = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
      return self.medium

  def get_absolute_url(self):
    return reverse('medium_detail', kwargs={'pk': self.id})

class Character(models.Model):
  name = models.CharField(max_length=100)
  media = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  age = models.CharField(max_length=20)
  pronoun = models.CharField(max_length=10)
  medium = models.ManyToManyField(Medium)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('characters_detail', kwargs={'character_id': self.id})


class Title(models.Model):
  title = models.CharField(max_length=100)
  date = models.DateField('Release Date')
  character = models.ForeignKey(Character, on_delete=models.CASCADE)
  
  def __str__(self):
    return f"{self.title} ({self.date})"
  
  class Meta: 
    ordering = ['-date']


  

main_app/forms.py
from django.forms import ModelForm
from .models import Title

class TitleForm(ModelForm):
  class Meta:
    model = Title
    fields = ['date', 'title']

main_app/views.py
from django.shortcuts import render, redirect
# Create your views here.
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Character, Medium
from .forms import TitleForm

class Home(LoginView):
  template_name = 'home.html'

class CharacterCreate(LoginRequiredMixin, CreateView):
  model = Character
  fields = ['name', 'media', 'description', 'age', 'pronoun']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class CharacterUpdate(LoginRequiredMixin, UpdateView):
  model = Character
  fields = [ 'media', 'description', 'age', 'pronoun']

class CharacterDelete(LoginRequiredMixin, DeleteView):
  model = Character
  success_url = '/characters/'

class MediumCreate(LoginRequiredMixin, CreateView):
  model = Medium
  fields = '__all__'

class MediumList(LoginRequiredMixin, ListView):
  model = Medium

class MediumDetail(LoginRequiredMixin, DetailView):
  model = Medium

class MediumUpdate(LoginRequiredMixin, UpdateView):
  model = Medium
  fields = ['medium', 'color']

class MediumDelete(LoginRequiredMixin, DeleteView):
  model = Medium
  success_url = '/mediums/'



def about(request):
  return render(request, 'about.html')

@login_required
def characters_index(request):
  characters = Character.objects.filter(user=request.user)
  return render(request, 'characters/index.html', {'characters': characters})

@login_required
def characters_detail(request, character_id):
  character = Character.objects.get(id=character_id)
  medium_character_doesnt_have = Medium.objects.exclude(id__in = character.medium.all().values_list('id'))
  title_form = TitleForm()
  return render(request, 'characters/detail.html', {'character' : character, 'title_form': title_form, 'medium': medium_character_doesnt_have})

@login_required
def add_title(request, character_id):
  form = TitleForm(request.POST)
  if form.is_valid():
    new_title = form.save(commit=False)
    new_title.character_id = character_id
    new_title.save()
  return redirect('characters_detail', character_id=character_id)

@login_required
def assoc_medium(request, character_id, medium_id):
  Character.objects.get(id=character_id).medium.add(medium_id)
  return redirect('characters_detail', character_id=character_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in
      login(request, user)
      return redirect('characters_index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)
  # Same as: return render(request, 'signup.html', {'form': form, 'error_message': error_message})

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Character Collector</h1>
<hr />
<p class="page-content">
  Keep track of your favorite fictional fellows in the Character Compendium! You can add characters, the titles they appear in, and the mediums that they live in!
</p>

{% endblock content%}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/favicon.ico' %}"
  >
  <title>Character Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
      <a href="/" style="text-align:center;text-decoration:none;color:black;font-size:larger">
        <h3 class="header-logo-container">The Character Compendium</h3>
      </a>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'characters_index' %}">All Characters</a></li>
        <li><a href={% url 'medium_index' %}> All Mediums</a></li>
        <li><a href={% url 'characters_create' %}>Add a Character</a></li>
        <li><a href={% url 'medium_create' %}> Add a Medium</a></li>
        <li><a href={% url 'about' %}>About</a></li>
        <li><a href={% url 'logout' %}>Log out</a></li>
        {% else %}
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'home' %}">Login</a></li>
        <li><a href="{% url 'signup' %}">Sign up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/characters/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/characters/character-detail.css' %}"
/>
<script defer src="{% static 'js/character-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="character-container">
  <div class="character-img">
  </div>
  <div class="character-details">
    <h1>{{ character.name }}</h1>
    <p>Age: {{ character.age }}</p>
    <p>{{ character.pronoun }} comes from {{ character.media }}.</p>
    <p><small>{{ character.description }}</small></p>
    <div class="character-actions">
      <a href="{% url 'characters_update' character.id%}" class="btn warn">Edit</a>
      <a href="{% url 'characters_delete' character.id%}" class="btn danger">Delete</a>
    </div>
  </div>
  </section>
  <div class="title-medium-container">
    <section class="titles">
      <div class="subsection-title">
        <h2>Appears In:</h2>
    </div>

    <h3>Titles</h3>
    {% if character.title_set.all.count %}
    <table>
      <thead>
        <tr><th>Title</th><th>Release Date</th></tr>
      </thead>
      <tbody>
        {% for title in character.title_set.all %}
          <tr>
            <td>{{title.title}}</td>
            <td>{{title.date}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="subsection-content">
      <p>Add titles that {{character.name}} appears in!</p>
    </div>
    {% endif %}
    
    <h3>Add a Title</h3>
    <form
      action="{% url 'add_title' character.id %}"
      method="post" 
      class="subsection-content"
    >
      {% csrf_token %}
      {{ title_form.as_p }}
      <button type="submit" class="btn submit">Add Title</button>
    </form>
  </section>
  <section class="mediums">
    <div class="subsection-title">
      <h2>Mediums</h2>
    </div>
    <h3>{{ character.name }} lives in:</h3>
    <div class="subsection-content">
      {% if character.medium.count %}
        {% for medium in character.medium.all %}
          <div class="sig-container">
            <div 
              class="color-block"
              style="background-color: {{ medium.color }}"
            ></div>
            <a href="{% url 'medium_detail' medium.id %}">
              <p>{{ medium.medium }}</p>
            </a>
          </div>
        {% endfor %}
      {% else %}
        <p class="no-mediums">{{character.name}} doesn't have any mediums yet 😞</p>
      {% endif %}
    </div>
    <h3>Available Mediums</h3>
      <div class="subsection-content">
        {% if medium.count %}
          {% for medium in medium.all %}
            <div class="sig-container">
              <div 
                class="color-block"
                style="background-color: {{ medium.color }}"
              ></div>
              <a href="{% url 'medium_detail' medium.id %}">
                <p> {{ medium.medium }}</p>
              </a>
              <form action="{% url 'assoc_medium' character.id medium.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn submit">Add medium</button>
              </form>
            </div>
          {% endfor %}
        {% else %}
          <p class="all-mediums">
            {{character.name}} already has all the available mediums 🥳
          </p>
        {% endif %}
      </div>
    </section>
  </div>
    </div>
  </section>

</div>

{% endblock %}

main_app/templates/characters/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/characters/character-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Character List 🕵️‍♂️🧙‍♀️👩‍🎤</h1>

</section>

<section class="card-container">
  {% for character in characters %}
  <div class="card">
    <a href="/characters/{{ character.id }}">
      <div class="card-content">
        <div class="card-img-container">
        </div>
        <h2 class="card-title">{{ character.name }}</h2>
        <p>Age: {{ character.age }}</p>
        <p>{{ character.pronoun }} comes from {{ character.media }}.</p>
        <p><small>{{ character.description }}</small></p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <img 
    src="{% static 'images/header-logo.png' %}" 
    alt="Character Collector Logo"
  />
</section>
{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Character? 😵</h1>
</div>
<h2>Are you sure you want to delete {{ character.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'characters_detail' character.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/character_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  {% if character %}
  <h1>Edit {{character.name}}</h1>
  {% else %}
  <h1>Add a Character 👥</h1>
  {% endif %}
</div>
{% comment %} 
  Leaving the action empty makes the form post to the same url used to display it
{% endcomment %}
<form action="" method="post" class="form-container">
  {% comment %} 
    Django requires the following for security purposes
  {% endcomment %}
  {% csrf_token %}
  <table>
    {% comment %}
      Render the inputs inside of <tr>s & <td>s
    {% endcomment %}
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/medium_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Medium? 🤕</h1>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'medium_detail' medium.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/medium_detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/toys/medium-detail.css' %}"
/>
{% endblock %}

{% block content %}
  
<div class="card" style="border-color: {{ medium.color }}">
  <div class="card-bg" style="background-color: {{ medium.color }}"></div>
  <div class="card-content">
    <h2>{{ medium.medium }}</h2>
  </div>
</div>
<a href="{% url 'medium_update' medium.id %}" class="btn warn">Edit</a>
<a href="{% url 'medium_delete' medium.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/medium_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}
<div class="page-header">
  {% if object %}
    <h1>Edit {{object.medium}} 👾🎭📚</h1>
  {% else %}
    <h1>Add a Medium 👾🎭📚</h1>
  {% endif %}
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/medium_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/medium/medium-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>All Mediums  🎥  👾 📼</h1>
</section>

<section class="card-container">
  {% for medium in medium_list %}
  <div class="card" style="border-color: {{ medium.color }}">
    <div class="card-bg" style="background-color: {{ medium.color }}"></div>
    <a href="{% url 'medium_detail' medium.id %}">
      <div class="card-content">
        <h2>{{ medium.medium }}</h2>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up 👤🤳</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}